# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://touko.moe/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
nav-title: Touko - Index
title: Touko Hoshino
# Description of the Site
description: A Ph. D. student in the area of computer networks. <br/> Formerly a full-stack developer.
# URL of Image of the Site
site-image: /assets/images/kamakura_coast-min.jpg
# Keywords of the Site
site-keywords: Tech, Network, Research
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/kamakura_coast-min.jpg

blog-url: https://wasteland.touko.moe/
cv-url: https://zxc.fyi/
blog-rss: https://wasteland.touko.moe/atom.xml

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: i@insky.jp
weibo_username: OranL
telegram_username: touko
facebook_username:
twitter_username: HoshinoTouko
instagram_username: HoshinoTouko
linkedin_username: czx
github_username:  HoshinoTouko
youtube_channel_id:
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: kinqp9u7zy7lfqv1jgj66efna

# Google Analytics
google-analytics: G-CCGL1Y7HLP

# Disqus
disqus-shortname: touko-blog-cover

# Name of the Author
author-name: Touko Hoshino
# URL for the Image of the Author
author-image: /assets/images/logo.png
# 60 Words About the Author
author-about: I am currently a Ph. D. candidate at Fudan University, working on computer network, distributed system, and datacenter network. <br/> I am a DIYer who enjoys computer hardware, 3D printing, computing clusters, small aircraft, and amateur radio. <br/> I love traveling and exploring.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/HoshinoTouko

footer-bio: My life's struggle is driven by the pursuit of truth and freedom.

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
